[env:pico_w_udp_uart_bridge]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico_w
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
build_flags =
  -DTARS_WIFI_SSID=\"TARS-PICO-BRIDGE\"
  -DTARS_WIFI_PASSWORD=\"tarsbridge\"
  -DTARS_UDP_PORT=15120
  -DTARS_UART_BAUD=115200
  -DTARS_UART_TX_PIN=4
  -DTARS_UART_RX_PIN=5
